version: "3"
services: 
  python-server:
    image: hello_server:2.3
    ports:
      - "80:8080"
    networks:
      - default

  redis:
    image: "redis:alpine"
    networks:
      - default

networks:
  default:
