version: "3"
services: 
  python-server:
    image: hello_server:2.3
    ports:
      - "80:8080"
    networks:
      - default
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 50M


  redis:
    image: "redis:alpine"
    networks:
      - default

networks:
  default:
